version: 2
jobs:
  build:
    name: Build
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies

      - restore_cache:
          keys:
          - v1-dependencies-cli-{{ checksum "packages/cli/package.json" }}
          - v1-dependencies-cli

      - restore_cache:
          keys:
          - v1-dependencies-core-{{ checksum "packages/lib-js-core/package.json" }}
          - v1-dependencies-core

      - restore_cache:
          keys:
          - v1-dependencies-client-{{ checksum "packages/lib-js-client/package.json" }}
          - v1-dependencies-client

      - restore_cache:
          keys:
          - v1-dependencies-validate-{{ checksum "packages/lib-js-validate/package.json" }}
          - v1-dependencies-validate

      - restore_cache:
          keys:
          - v1-dependencies-test-{{ checksum "packages/lib-js-test/package.json" }}
          - v1-dependencies-test

      - restore_cache:
          keys:
          - v1-dependencies-template-project-empty-{{ checksum "packages/template-project-empty/package.json" }}
          - v1-dependencies-template-project-empty

      - restore_cache:
          keys:
          - v1-dependencies-template-project-hello-{{ checksum "packages/template-project-hello/package.json" }}
          - v1-dependencies-template-project-hello

      - restore_cache:
          keys:
          - v1-dependencies-template-socket-es6-{{ checksum "packages/template-socket-es6/package.json" }}
          - v1-dependencies-template-socket-es6

      - restore_cache:
          keys:
          - v1-dependencies-registry-organization-{{ checksum "packages/registry/syncano/organization/package.json" }}
          - v1-dependencies-registry-organization

      - restore_cache:
          keys:
          - v1-dependencies-registry-registry-{{ checksum "packages/registry/syncano/registry/package.json" }}
          - v1-dependencies-registry-registry

      - restore_cache:
          keys:
          - v1-dependencies-test-tools-{{ checksum "packages/test-tools/package.json" }}
          - v1-dependencies-test-tools

      - restore_cache:
          keys:
          - v1-dependencies-registry-{{ checksum "packages/registry/package.json" }}
          - v1-dependencies-registry

      - run: yarn install
      - run: yarn run bootstrap

      - save_cache:
          paths:
            - node_modules
            - .yarn-cache
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
            - packages/cli/node_modules
          key: v1-dependencies-cli-{{ checksum "packages/cli/package.json" }}

      - save_cache:
          paths:
            - packages/lib-js-core/node_modules
          key: v1-dependencies-core-{{ checksum "packages/lib-js-core/package.json" }}

      - save_cache:
          paths:
            - packages/lib-js-client/node_modules
          key: v1-dependencies-client-{{ checksum "packages/lib-js-client/package.json" }}

      - save_cache:
          paths:
            - packages/lib-js-validate/node_modules
          key: v1-dependencies-validate-{{ checksum "packages/lib-js-validate/package.json" }}

      - save_cache:
          paths:
            - packages/lib-js-test/node_modules
          key: v1-dependencies-test-{{ checksum "packages/lib-js-test/package.json" }}

      - save_cache:
          paths:
            - packages/template-project-empty/node_modules
          key: v1-dependencies-template-project-empty-{{ checksum "packages/template-project-empty/package.json" }}

      - save_cache:
          paths:
            - packages/template-project-empty/node_modules
          key: v1-dependencies-template-project-empty-{{ checksum "packages/template-project-empty/package.json" }}

      - save_cache:
          paths:
            - packages/template-project-hello/node_modules
          key: v1-dependencies-template-project-hello-{{ checksum "packages/template-project-hello/package.json" }}

      - save_cache:
          paths:
            - packages/template-socket-es6/node_modules
          key: v1-dependencies-template-socket-es6-{{ checksum "packages/template-socket-es6/package.json" }}

      - save_cache:
          paths:
            - packages/registry/syncano/organization/node_modules
          key: v1-dependencies-registry-organization-{{ checksum "packages/registry/syncano/organization/package.json" }}

      - save_cache:
          paths:
            - packages/registry/syncano/registry/node_modules
          key: v1-dependencies-registry-registry-{{ checksum "packages/registry/syncano/registry/package.json" }}

      - save_cache:
          paths:
            - packages/registry/node_modules
          key: v1-dependencies-registry-{{ checksum "packages/registry/package.json" }}

      - save_cache:
          paths:
            - packages/test-tools/node_modules
          key: v1-dependencies-test-tools-{{ checksum "packages/test-tools/package.json" }}

      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  test_unit:
    name: Unit Tests
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn run test:unit
      - run: yarn run report:coverage

  test_e2e_client:
    name: E2E Tests
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo/packages/lib-js-client/

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn run test:e2e

  test_e2e_validate:
    name: E2E Tests
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo/packages/lib-js-validate/

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn run test:e2e

  test_e2e_core:
    name: E2E Tests
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo/packages/lib-js-core/

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn run test:e2e

  test_e2e_registry:
    name: E2E Tests
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo/packages/cli

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: SYNCANO_SOCKET_REGISTRY_INSTANCE=${REGISTRY_TEST_SYNCANO_PROJECT_INSTANCE}-${CIRCLE_SHA1} yarn run test:e2e:registry

  test_e2e_hosting:
    name: E2E Tests
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo/packages/cli

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn run test:e2e:hosting

  test_e2e_socket:
    name: E2E Tests
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo/packages/cli

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn run test:e2e:socket

  test_e2e_anonymous:
    name: E2E Tests
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo/packages/cli

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn run test:e2e:anonymous

  test_e2e_instance:
    name: E2E Tests
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo/packages/cli

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn run test:e2e:instance

  test_e2e_deploy:
    name: E2E Tests
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo/packages/cli

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn run test:e2e:deploy

  test_e2e_config:
    name: E2E Tests
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo/packages/cli

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn run test:e2e:config

  test_lint:
    name: Linter
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn run lint

  deploy_docs:
    name: Deploying Docs
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo 'export SYNCANO_AUTH_KEY=${CANARY_SYNCANO_AUTH_KEY}' >> $BASH_ENV
      - run: echo 'export SYNCANO_PROJECT_INSTANCE=${CANARY_SYNCANO_PROJECT_INSTANCE}' >> $BASH_ENV
      - run: node packages/cli/lib/cli.js deploy
      - run: node packages/cli/lib/cli.js hosting sync docs
      - run: node packages/cli/lib/cli.js hosting sync cookbook
      - run: node packages/cli/lib/cli.js hosting sync cheatsheet

  deploy_test_registry:
    name: Deploying Test Registry
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo/packages/registry

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: echo 'export REGISTRY_TEST_SYNCANO_PROJECT_INSTANCE=${REGISTRY_TEST_SYNCANO_PROJECT_INSTANCE}-${CIRCLE_SHA1}' >> $BASH_ENV
      - run: sh ./bin/deploy-staging

  deploy_registry:
    name: Deploy Production Registry
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo/packages/registry

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: sh ./bin/deploy

  delete_registry:
    name: Delete Test Registry
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo/packages/registry

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: SYNCANO_AUTH_KEY=${REGISTRY_TEST_SYNCANO_AUTH_KEY} npx s instance delete ${REGISTRY_TEST_SYNCANO_PROJECT_INSTANCE}-${CIRCLE_SHA1}

  publish:
    name: Publish packages to NPM
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: npx npm-cli-login -u $NPM_USER -p $NPM_PASS -e $NPM_EMAIL -s syncano
      - run: yarn run changelog
      - run: npx lerna publish --canary --yes

  codecov:
    name: Send Codecov report
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - restore_cache:
          key: v1-repo-units-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn run report:coverage

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test_lint:
          requires:
            - build
      - test_unit:
          requires:
            - build
      - test_e2e_validate:
          requires:
            - build
      - test_e2e_client:
          requires:
            - build
      - test_e2e_instance:
          requires:
            - build
      - test_e2e_deploy:
          requires:
            - build
      - test_e2e_config:
          requires:
            - build
      - test_e2e_anonymous:
          requires:
            - build
      - test_e2e_hosting:
          requires:
            - build
      - test_e2e_socket:
          requires:
            - build
      - deploy_test_registry:
          requires:
            - build
      - test_e2e_registry:
          requires:
            - build
            - deploy_test_registry
      - test_e2e_core:
          requires:
            - build
      - delete_registry:
          requires:
            - test_e2e_registry
      - deploy_docs:
          requires:
            - build
            - test_e2e_instance
            - test_e2e_validate
            - test_e2e_client
            - test_e2e_registry
            - test_e2e_socket
            - test_e2e_hosting
            - test_e2e_core
            - test_e2e_anonymous
            - test_e2e_config
            - test_e2e_deploy
            - test_lint
            - test_unit
          filters:
            branches:
              only: master
      - publish:
          requires:
            - test_e2e_instance
            - test_e2e_validate
            - test_e2e_client
            - test_e2e_registry
            - test_e2e_socket
            - test_e2e_hosting
            - test_e2e_core
            - test_e2e_anonymous
            - test_e2e_config
            - test_e2e_deploy
            - test_lint
            - test_unit
          filters:
            branches:
              only: master
      - deploy_registry:
          requires:
            - publish
          filters:
            branches:
              only: /\d/
