version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: sudo npm install -g yarn
      - run: sudo npm install -g lerna
      - run: lerna bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
            - packages/cli/node_modules
          key: v1-dependencies-cli-{{ checksum "packages/cli/package.json" }}

      - save_cache:
          paths:
            - packages/lib-js-socket/node_modules
          key: v1-dependencies-socket-{{ checksum "packages/lib-js-socket/package.json" }}

      - save_cache:
          paths:
            - packages/lib-js-client/node_modules
          key: v1-dependencies-client-{{ checksum "packages/lib-js-client/package.json" }}

      - save_cache:
          paths:
            - packages/lib-js-validate/node_modules
          key: v1-dependencies-validate-{{ checksum "packages/lib-js-validate/package.json" }}

      - save_cache:
          paths:
            - packages/lib-js-test/node_modules
          key: v1-dependencies-test-{{ checksum "packages/lib-js-test/package.json" }}


      # run tests!
      - run: yarn run test:unit
      - run: yarn run test:e2e
