version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - restore_cache:
          keys:
          - v1-dependencies-cli-{{ checksum "packages/cli/package.json" }}
          - v1-dependencies-cli-

      - restore_cache:
          keys:
          - v1-dependencies-core-{{ checksum "packages/lib-js-core/package.json" }}
          - v1-dependencies-core-

      - restore_cache:
          keys:
          - v1-dependencies-client-{{ checksum "packages/lib-js-client/package.json" }}
          - v1-dependencies-client

      - restore_cache:
          keys:
          - v1-dependencies-validate-{{ checksum "packages/lib-js-validate/package.json" }}
          - v1-dependencies-validate

      - restore_cache:
          keys:
          - v1-dependencies-test-{{ checksum "packages/lib-js-test/package.json" }}
          - v1-dependencies-test

      - run: sudo npm install -g yarn
      - run: sudo npm install -g lerna
      - run: lerna bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - save_cache:
          paths:
            - packages/cli/node_modules
          key: v1-dependencies-cli-{{ checksum "packages/cli/package.json" }}

      - save_cache:
          paths:
            - packages/lib-js-core/node_modules
          key: v1-dependencies-core-{{ checksum "packages/lib-js-core/package.json" }}

      - save_cache:
          paths:
            - packages/lib-js-client/node_modules
          key: v1-dependencies-client-{{ checksum "packages/lib-js-client/package.json" }}

      - save_cache:
          paths:
            - packages/lib-js-validate/node_modules
          key: v1-dependencies-validate-{{ checksum "packages/lib-js-validate/package.json" }}

      - save_cache:
          paths:
            - packages/lib-js-test/node_modules
          key: v1-dependencies-test-{{ checksum "packages/lib-js-test/package.json" }}

  test:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      # run tests!
      - run: yarn run lint
      - run: yarn run test:unit
      - run: yarn run test:e2e

  deploy:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - run: lerna publish --canary
      - run: npx s deploy
      - run: npx s hosting sync docs
      - run: npx s hosting sync cookbook
      - run: npx s hosting sync cheatsheet

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
        requires:
          - build
      - deploy:
        requires:
          - build
          - test
        filtr:
          branches:
            only: master
